import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import grain from '@/public/image/download.jpeg'
import { EdgeStoreProvider } from "@/lib/edgestore";

import { BackgroundBeamsDemo } from "@/component/ui/BackgroundBeamsDemo";
import Header from "@/component/ui/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black text-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-black-100 w-full overflow-x-hidden`}
      > 
        <Header  />
        <EdgeStoreProvider>
          {children}
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
